### ISSUE TITLE
How to config mumudvb

### ISSUE THREAD

**Issue by zickkeen** [braice/MuMuDVB#144] opened 2016-12-05 18:03 UTC
I use dvb-s2 for intelsat-19, and if I start mumudvb always error:

> MuMuDVB Version 2.0.0_20150614_mumudvb2
>  --- Build information ---
> Built with CAM support.
> Built without SCAM support.
> Built with ATSC support.
> Built with ATSC long channel names support.
> Built with support for DVB API Version 5.10.
> Built with support for DVB-T2.
> ---------
> Originally based on dvbstream 0.6 by (C) Dave Chapman 2001-2004
> Released under the GPL.
> Latest version available from http://mumudvb.braice.net/
> Project from the cr@ns (http://www.crans.org)
> by Brice DUBOST (mumudvb@braice.net)
> 
> Deb2:  Main:  ==== Configuration file ====
> Deb2:  Main:  001 delivery_system=DVBS2
> Deb2:  Main:  002 freq=3780
> Deb2:  Main:  003 pol=h
> Deb2:  Main:  004 srate=30000
> Deb2:  Main:  005 coderate=3/4
> Deb2:  Main:  006 sap_default_group=My channels
> Deb2:  Main:  ============ done ===========
> Info:  Tune:  You will use DVB API version 5 for tuning your card.
> Info:  Main:  ========== End of configuration, MuMuDVB version 2.0.0_20150614_mumudvb2 is starting ==========
> WARN:  Main:  Can't create /var/run/mumudvb/channels_streamed_adapter0_tuner0: No such file or directory
> WARN:  Main:  Can't create /var/run/mumudvb/channels_unstreamed_adapter0_tuner0: No such file or directory
> Info:  Main:  Streaming. Freq 3780000
> ERRO:  DVB:  FRONTEND DEVICE: /dev/dvb/adapter0/frontend0 : No such file or directory
> ERRO:  Tune:  FE_GET_INFO: Bad file descriptor
> Info:  Main:  Tuning issue, card 0
> Info:  Main:  Closing cleanly. Error 7
> Info:  Main:  ========== MuMuDVB version 2.0.0_20150614_mumudvb2 is stopping with ExitCode 7 ==========
> root@streamer:/home/iptv#

Please anyone help me.

**Comment by zavazingo** [comment] 2016-12-05 20:41
Seems there is nothing on that frequency.

**Comment by lobeck** [comment] 2016-12-05 22:51
Looks like a driver issue, as it can't open the tuner

can you do a `ls -l /dev/dvb/adapter*/`

**Comment by zickkeen** [comment] 2016-12-07 11:29
I've done reconfig of the driver.
now the error like this:

> Iptv@streamer:~$ sudo mumudvb -d -vvv -c mumu.conf --card 0
> MuMuDVB Version 2.0.0_20150614_mumudvb2
>  --- Build information ---
> Built with CAM support.
> Built without SCAM support.
> Built with ATSC support.
> Built with ATSC long channel names support.
> Built with support for DVB API Version 5.10.
> Built with support for DVB-T2.
> ---------
> Originally based on dvbstream 0.6 by (C) Dave Chapman 2001-2004
> Released under the GPL.
> Latest version available from http://mumudvb.braice.net/
> Project from the cr@ns (http://www.crans.org)
> By Brice DUBOST (mumudvb@braice.net)
> Deb2:  Main:  ==== Configuration file ====
> Deb2:  Main:  001 delivery_system=DVBS2
> Deb2:  Main:  002 freq=3780
> Deb2:  Main:  003 pol=h
> Deb2:  Main:  004 srate=30000
> Deb2:  Main:  005 coderate=3/4
> Deb2:  Main:  006 sap_default_group=My channels
> Deb2:  Main:  ============ done ===========
> Info:  Tune:  You will use DVB API version 5 for tuning your card.
> Info:  Main:  ========== End of configuration, MuMuDVB version 2.0.0_20150614_mumudvb2 is starting ==========
> Info:  Main:  Streaming. Freq 3780000
> Info:  Tune:  Using DVB card "TurboSight TBS 6904 DVB-S/S2 " tuner 0
> Info:  Tune:  Tuning DVB-S to Freq: 5970000 kHz, LO frequency 9750000 kHz Pol:H Srate=30000000, LNB number: 0
> Info:  Tune:  LNB voltage 18V
> Info:  Tune:  DISEQC SETTING SUCCEDED
> Info:  Tune:  Tuning With DVB-API version 5. delivery system : 6
> Info:  Tune:  Stream_id = 0, stream id with PLS parameters 0
> ERRO:  Tune:  FE_SET_PROPERTY failed : Invalid argument
> Info:  Main:  Tuning issue, card 0
> Info:  Main:  Closing cleanly. Error 7
> Info:  Main:  ========== MuMuDVB version 2.0.0_20150614_mumudvb2 is stopping with ExitCode 7 ==========

And this is my list card:
> iptv@streamer:~$ ls -l > /dev/dvb/adapter*/
> /dev/dvb/adapter0/:
> total 0
> crw-rw---- 1 root video 212, 0 Dec  7 19:16 demux0
> crw-rw---- 1 root video 212, 1 Dec  7 19:16 dvr0
> crw-rw---- 1 root video 212, 3 Dec  7 19:16 frontend0
> crw-rw---- 1 root video 212, 2 Dec  7 19:16 net0
>
> /dev/dvb/adapter1/:
> total 0
> crw-rw---- 1 root video 212, 4 Dec  7 19:16 demux0
> crw-rw---- 1 root video 212, 5 Dec  7 19:16 dvr0
> crw-rw---- 1 root video 212, 7 Dec  7 19:16 frontend0
> crw-rw---- 1 root video 212, 6 Dec  7 19:16 net0
>
> /dev/dvb/adapter2/:
> total 0
> crw-rw---- 1 root video 212,  8 Dec  7 19:16 demux0
> crw-rw---- 1 root video 212,  9 Dec  7 19:16 dvr0
> crw-rw---- 1 root video 212, 11 Dec  7 19:16 frontend0
> crw-rw---- 1 root video 212, 10 Dec  7 19:16 net0
>
> /dev/dvb/adapter3/:
> total 0
> crw-rw---- 1 root video 212, 12 Dec  7 19:16 demux0
> crw-rw---- 1 root video 212, 13 Dec  7 19:16 dvr0
> crw-rw---- 1 root video 212, 15 Dec  7 19:16 frontend0
> crw-rw---- 1 root video 212, 14 Dec  7 19:16 net0

**Comment by braice** [comment] 2016-12-10 15:51
On Dec 7, 2016 6:29 AM, "Zick Keen" <notifications@github.com> wrote:

I've done reconfig of the driver.
now the error like this:

Iptv@streamer:~$ sudo mumudvb -d -vvv -c mumu.conf --card 0 Info: Tune:
Tuning With DVB-API version 5. delivery system : 6
Info: Tune: Stream_id = 0, stream id with PLS parameters 0
ERRO: Tune: FE_SET_PROPERTY failed : Invalid argument

Info: Main: Tuning issue, card 0
Info: Main: Closing cleanly. Error 7
Info: Main: ========== MuMuDVB version 2.0.0_20150614_mumudvb2 is stopping
with ExitCode 7 ==========



Hello,

can you run
mumudvb -lvvv

it will help see what your card can do

brice

**Comment by zickkeen** [comment] 2016-12-11 00:16
> ~$ sudo mumudvb -lvvv
> MuMuDVB Version 1.7.1
>  --- Build information ---
> Built with CAM support.
> Built without transcoding support.
> Built with ATSC support.
> Built with ATSC long channel names support.
> Built with support for DVB API Version 5.
> ---------
> Originally based on dvbstream 0.6 by (C) Dave Chapman 2001-2004
> Released under the GPL.
> Latest version available from http://mumudvb.braice.net/
> Project from the cr@ns (http://www.crans.org)
> by Brice DUBOST (mumudvb@braice.net)
> 
> Info:  DVB:  ==================================
> Info:  DVB:          DVB CARDS LISTING
> Info:  DVB:  ==================================
> 
> Info:  DVB:  =========== Card 0 - Tuner 0 ===========
> Info:  DVB:   Frontend : TurboSight TBS 6904 DVB-S/S2
> Info:  DVB:   Satellite (DVB-S) card
> Info:  DVB:   Frequency: 950000 kHz to 2150000 kHz
> Info:  DVB:   Symbol rate: 1000 k symbols/s to 45000 k symbols/s
> Info:  DVB:
> 
> Info:  DVB:  =========== Card 1 - Tuner 0 ===========
> Info:  DVB:   Frontend : TurboSight TBS 6904 DVB-S/S2
> Info:  DVB:   Satellite (DVB-S) card
> Info:  DVB:   Frequency: 950000 kHz to 2150000 kHz
> Info:  DVB:   Symbol rate: 1000 k symbols/s to 45000 k symbols/s
> Info:  DVB:
> 
> Info:  DVB:  =========== Card 2 - Tuner 0 ===========
> Info:  DVB:   Frontend : TurboSight TBS 6904 DVB-S/S2
> Info:  DVB:   Satellite (DVB-S) card
> Info:  DVB:   Frequency: 950000 kHz to 2150000 kHz
> Info:  DVB:   Symbol rate: 1000 k symbols/s to 45000 k symbols/s
> Info:  DVB:
> 
> Info:  DVB:  =========== Card 3 - Tuner 0 ===========
> Info:  DVB:   Frontend : TurboSight TBS 6904 DVB-S/S2
> Info:  DVB:   Satellite (DVB-S) card
> Info:  DVB:   Frequency: 950000 kHz to 2150000 kHz
> Info:  DVB:   Symbol rate: 1000 k symbols/s to 45000 k symbols/s
> Info:  DVB:
> 
> ~$

**Comment by braice** [comment] 2016-12-11 01:19
Please use mumudvb 2 from github

**Comment by zickkeen** [comment] 2016-12-11 03:47
> # sudo mumudvb -lvvv
> MuMuDVB Version 2.0.0_20150614_mumudvb2
>  --- Build information ---
> Built with CAM support.
> Built without SCAM support.
> Built with ATSC support.
> Built with ATSC long channel names support.
> Built with support for DVB API Version 5.10.
> Built with support for DVB-T2.
> ---------
> Originally based on dvbstream 0.6 by (C) Dave Chapman 2001-2004
> Released under the GPL.
> Latest version available from http://mumudvb.braice.net/
> Project from the cr@ns (http://www.crans.org)
> by Brice DUBOST (mumudvb@braice.net)
> 
> Info:  DVB:  ==================================
> Info:  DVB:          DVB CARDS LISTING
> Info:  DVB:  ==================================
> Deb1:  DVB:  found adapter 3
> Deb1:  DVB:  found adapter 2
> Deb1:  DVB:  found adapter 1
> Deb1:  DVB:  found adapter 0
> Deb1:  DVB:     Card 0 found Frontend 0
> Info:  DVB:  =========== Card 0 - Tuner 0 ===========
> Info:  DVB:   Frontend : TurboSight TBS 6904 DVB-S/S2
> Info:  DVB:   Satellite (DVB-S) card
> Info:  DVB:   Frequency: 950000 kHz to 2150000 kHz
> Info:  DVB:   Symbol rate: 1000 k symbols/s to 45000 k symbols/s
> Deb0:  DVB:   == Card capabilities ==
> Deb1:  DVB:  caps 0x500006ff
> Deb0:  DVB:  FE_CAN_INVERSION_AUTO
> Deb0:  DVB:  FE_CAN_FEC_1_2
> Deb0:  DVB:  FE_CAN_FEC_2_3
> Deb0:  DVB:  FE_CAN_FEC_3_4
> Deb0:  DVB:  FE_CAN_FEC_4_5
> Deb0:  DVB:  FE_CAN_FEC_5_6
> Deb0:  DVB:  FE_CAN_FEC_6_7
> Deb0:  DVB:  FE_CAN_FEC_7_8
> Deb0:  DVB:  FE_CAN_FEC_AUTO
> Deb0:  DVB:  FE_CAN_QPSK
> Deb0:  DVB:  FE_CAN_2G_MODULATION /* frontend supports '2nd generation modulation' (DVB-S2) */
> Deb0:  DVB:  FE_CAN_RECOVER /* frontend can recover from a cable unplug automatically */
> Info:  DVB:
> Deb1:  DVB:     Card 1 found Frontend 0
> Info:  DVB:  =========== Card 1 - Tuner 0 ===========
> Info:  DVB:   Frontend : TurboSight TBS 6904 DVB-S/S2
> Info:  DVB:   Satellite (DVB-S) card
> Info:  DVB:   Frequency: 950000 kHz to 2150000 kHz
> Info:  DVB:   Symbol rate: 1000 k symbols/s to 45000 k symbols/s
> Deb0:  DVB:   == Card capabilities ==
> Deb1:  DVB:  caps 0x500006ff
> Deb0:  DVB:  FE_CAN_INVERSION_AUTO
> Deb0:  DVB:  FE_CAN_FEC_1_2
> Deb0:  DVB:  FE_CAN_FEC_2_3
> Deb0:  DVB:  FE_CAN_FEC_3_4
> Deb0:  DVB:  FE_CAN_FEC_4_5
> Deb0:  DVB:  FE_CAN_FEC_5_6
> Deb0:  DVB:  FE_CAN_FEC_6_7
> Deb0:  DVB:  FE_CAN_FEC_7_8
> Deb0:  DVB:  FE_CAN_FEC_AUTO
> Deb0:  DVB:  FE_CAN_QPSK
> Deb0:  DVB:  FE_CAN_2G_MODULATION /* frontend supports '2nd generation modulation' (DVB-S2) */
> Deb0:  DVB:  FE_CAN_RECOVER /* frontend can recover from a cable unplug automatically */
> Info:  DVB:
> Deb1:  DVB:     Card 2 found Frontend 0
> Info:  DVB:  =========== Card 2 - Tuner 0 ===========
> Info:  DVB:   Frontend : TurboSight TBS 6904 DVB-S/S2
> Info:  DVB:   Satellite (DVB-S) card
> Info:  DVB:   Frequency: 950000 kHz to 2150000 kHz
> Info:  DVB:   Symbol rate: 1000 k symbols/s to 45000 k symbols/s
> Deb0:  DVB:   == Card capabilities ==
> Deb1:  DVB:  caps 0x500006ff
> Deb0:  DVB:  FE_CAN_INVERSION_AUTO
> Deb0:  DVB:  FE_CAN_FEC_1_2
> Deb0:  DVB:  FE_CAN_FEC_2_3
> Deb0:  DVB:  FE_CAN_FEC_3_4
> Deb0:  DVB:  FE_CAN_FEC_4_5
> Deb0:  DVB:  FE_CAN_FEC_5_6
> Deb0:  DVB:  FE_CAN_FEC_6_7
> Deb0:  DVB:  FE_CAN_FEC_7_8
> Deb0:  DVB:  FE_CAN_FEC_AUTO
> Deb0:  DVB:  FE_CAN_QPSK
> Deb0:  DVB:  FE_CAN_2G_MODULATION /* frontend supports '2nd generation modulation' (DVB-S2) */
> Deb0:  DVB:  FE_CAN_RECOVER /* frontend can recover from a cable unplug automatically */
> Info:  DVB:
> Deb1:  DVB:     Card 3 found Frontend 0
> Info:  DVB:  =========== Card 3 - Tuner 0 ===========
> Info:  DVB:   Frontend : TurboSight TBS 6904 DVB-S/S2
> Info:  DVB:   Satellite (DVB-S) card
> Info:  DVB:   Frequency: 950000 kHz to 2150000 kHz
> Info:  DVB:   Symbol rate: 1000 k symbols/s to 45000 k symbols/s
> Deb0:  DVB:   == Card capabilities ==
> Deb1:  DVB:  caps 0x500006ff
> Deb0:  DVB:  FE_CAN_INVERSION_AUTO
> Deb0:  DVB:  FE_CAN_FEC_1_2
> Deb0:  DVB:  FE_CAN_FEC_2_3
> Deb0:  DVB:  FE_CAN_FEC_3_4
> Deb0:  DVB:  FE_CAN_FEC_4_5
> Deb0:  DVB:  FE_CAN_FEC_5_6
> Deb0:  DVB:  FE_CAN_FEC_6_7
> Deb0:  DVB:  FE_CAN_FEC_7_8
> Deb0:  DVB:  FE_CAN_FEC_AUTO
> Deb0:  DVB:  FE_CAN_QPSK
> Deb0:  DVB:  FE_CAN_2G_MODULATION /* frontend supports '2nd generation modulation' (DVB-S2) */
> Deb0:  DVB:  FE_CAN_RECOVER /* frontend can recover from a cable unplug automatically */
> Info:  DVB:

When starting:
> sudo mumudvb -vvv -d -c mumudvb.conf
> MuMuDVB Version 2.0.0_20150614_mumudvb2
>  --- Build information ---
> Built with CAM support.
> Built without SCAM support.
> Built with ATSC support.
> Built with ATSC long channel names support.
> Built with support for DVB API Version 5.10.
> Built with support for DVB-T2.
> ---------
> Originally based on dvbstream 0.6 by (C) Dave Chapman 2001-2004
> Released under the GPL.
> Latest version available from http://mumudvb.braice.net/
> Project from the cr@ns (http://www.crans.org)
> by Brice DUBOST (mumudvb@braice.net)
> 
> Deb2:  Main:  ==== Configuration file ====
> Deb2:  Main:  001 autoconfiguration=full
> Deb2:  Main:  002 freq=3747
> Deb2:  Main:  003 pol=h
> Deb2:  Main:  004 srate=11200
> Deb2:  Main:  005 sap=1
> Deb2:  Main:  006
> Deb2:  Main:  ============ done ===========
> Info:  SAP:  Sap announces will be sent
> Info:  Main:  Autoconfiguration, we activate PAT rewriting. if you want to disable it see the README.
> Info:  Main:  Autoconfiguration, we activate SDT rewriting. if you want to disable it see the README.
> Info:  Main:  ========== End of configuration, MuMuDVB version 2.0.0_20150614_mumudvb2 is starting ==========
> Info:  Main:  Streaming. Freq 3747000
> Info:  Tune:  Using DVB card "TurboSight TBS 6904 DVB-S/S2 " tuner 0
> Info:  Tune:  Tuning DVB-S to Freq: 6003000 kHz, LO frequency 9750000 kHz Pol:H Srate=11200000, LNB number: 0
> Info:  Tune:  LNB voltage 18V
> Info:  Tune:  DISEQC SETTING SUCCEDED
> ERRO:  Tune:  ERROR tuning channel : Invalid argument
> Info:  Main:  Tuning issue, card 0
> Info:  Main:  Closing cleanly. Error 7
> Info:  Main:  ========== MuMuDVB version 2.0.0_20150614_mumudvb2 is stopping with ExitCode 7 ==========

**Comment by m0yellow** [comment] 2017-01-21 20:13
the error ist here ...

> Info: Main: Streaming. Freq 3747000
> Info: Tune: Using DVB card "TurboSight TBS 6904 DVB-S/S2 " tuner 0
> Info: Tune: Tuning DVB-S to Freq: 6003000 kHz, LO frequency 9750000 kHz Pol:H 

This can't be right.
LO frequency is way to high for that.
can you set 
lnb_type = standard
lnb_lof_standard = ????

manually? You need to set the local oscillator frequency to a value of your LNB.
This should tune your card to the right frequency.

**Comment by Infobarra** [comment] 2017-03-18 14:51
Hi lads

i am getting the same exact issue i have folder etc/mumudvb/ with specific card config inside example i am testing this channel 

this is the config

`delivery_system=DVBS2
freq=03928
pol=h
srate=03906
coderate=3/4
card=1
tunner=0
modulation=8PSK
rolloff=auto
lnb_type=standard
lnb_lof_low=5150
#lnb_lof_high=5950
pls_type=root`


and this is my file config i am using on mumudvb start

`DONTSTARTMUMU=false

#If you want to launch a command before mumudvb (for example for automatic configuration generation)
#LAUNCH_BEFORE_MUMU=""

#Options for mumudvb
DAEMON_OPTS=""

#The user to launch mumudvb
DAEMONUSER=_mumudvb

#Change this line to reflect your configuration
#Ex : ADAPTERS="0 1 2 4"
ADAPTERS="1"

#Location of the config files
MUMUDVB_CONF_1="/etc/mumudvb/card1.txt"


and this is the output log result


WARN:  Main:  Config issue : unknow symbol : DONTSTARTMUMU

WARN:  Main:  Config issue : unknow symbol : DAEMON_OPTS

WARN:  Main:  Config issue : unknow symbol : DAEMONUSER

WARN:  Main:  Config issue : unknow symbol : ADAPTERS

WARN:  Main:  Config issue : unknow symbol : MUMUDVB_CONF_1

Info:  Main:  ========== End of configuration, MuMuDVB version 2.0.0_20150614_mumudvb2 is starting ==========
Info:  Main:  Streaming. Freq 0
Info:  Tune:  Using DVB card "TurboSight TBS 6904 DVBS/S2 frontend" tuner 0
Info:  Tune:  Tuning DVB-S to Freq: 9750000 kHz, LO frequency 9750000 kHz Pol:
Info:  Tune:  LNB voltage 18V
Info:  Tune:  DISEQC SETTING SUCCEDED
ERRO:  Tune:  ERROR tuning channel : Invalid argument
Info:  Main:  Tuning issue, card 0
Info:  Main:  Closing cleanly. Error 7
Info:  Main:  ========== MuMuDVB version 2.0.0_20150614_mumudvb2 is stopping with ExitCode 7 ==========



Any idea of what might be the problem?
``

**Comment by braice** [comment] 2017-03-18 19:39
Hello

Each configuration item have to be in a separate line,

The configuration file you are trying to edit is for the init.d script not
mumudvb

So, take the config, put one item per line and use this as a configuration
file

Best

Brice


2017-03-18 10:51 GMT-04:00 Infobarra <notifications@github.com>:

**Comment by Infobarra** [comment] 2017-03-20 11:33
Hi braice

i am confused now..

which configuration are you talking about? the Tunner status for example?

because i am using one file.conf for each tunner separate, is this correct or is this wrong?

example i am using this configuration lets get all confusion sorte out..

1-  /etc/default/mumudvb

this i have the following config to start mumudvb

> #Mumudvb init config file
#
# This file is used to specify the locations of mumudvb config files for each card
#

DONTSTARTMUMU=false

#If you want to launch a command before mumudvb (for example for automatic configuration generation)
#LAUNCH_BEFORE_MUMU=""

#Options for mumudvb
DAEMON_OPTS=""

#The user to launch mumudvb
DAEMONUSER=_mumudvb

#Change this line to reflect your configuration
#Ex : ADAPTERS="0 1 2 4"
ADAPTERS="1"

#Location of the config files
MUMUDVB_CONF_0="/etc/mumudvb/card1.conf"



2- /etc/mumudvb/card1.conf

This is where i have my card1 channel tunner configuration

> ########## 

common_port=1234 
sap=1 
sap_default_group=MYGROUP 
rewrite_pat=1 
ip_http=172.10.0.1
port_http=8008

##########
card=1 
freq=3928 
pol=H 
srate=3906 
modulation=8PSK 
coderate=3/4 
delivery_system=DVBS2 
dvr_thread=1 
dvr_buffer_size=160 




3- then i execute under mumudvb user, the following cmd

 mumudvb -vvv -d -c /etc/default/mumudvb



It starts the init config in /etc/default/mumudvb.. and when it tries to tune the channel i get this information posted before

> WARN: Main: Config issue : unknow symbol : DONTSTARTMUMU

WARN: Main: Config issue : unknow symbol : DAEMON_OPTS

WARN: Main: Config issue : unknow symbol : DAEMONUSER

WARN: Main: Config issue : unknow symbol : ADAPTERS

WARN: Main: Config issue : unknow symbol : MUMUDVB_CONF_1

Info: Main: ========== End of configuration, MuMuDVB version 2.0.0_20150614_mumudvb2 is starting ==========
Info: Main: Streaming. Freq 0
Info: Tune: Using DVB card "TurboSight TBS 6904 DVBS/S2 frontend" tuner 0
Info: Tune: Tuning DVB-S to Freq: 9750000 kHz, LO frequency 9750000 kHz Pol:
Info: Tune: LNB voltage 18V
Info: Tune: DISEQC SETTING SUCCEDED
ERRO: Tune: ERROR tuning channel : Invalid argument
Info: Main: Tuning issue, card 0
Info: Main: Closing cleanly. Error 7
Info: Main: ========== MuMuDVB version 2.0.0_20150614_mumudvb2 is stopping with ExitCode 7 ==========

**Comment by Infobarra** [comment] 2017-03-20 11:37
so i am thinking that by executing the /etc/default/mumudvb  file

this will call inside the mumudvb file,  the other folder /etc/mumudvb/card1.conf  file where i have setup my tunner configuration for the specific TP am i wrong?

can you please give me some help on this?

**Comment by kslimani** [comment] 2017-03-20 12:06
@Infobarra the `/etc/default/mumudvb` is included by init script to setup default values. It is not a MuMuDVB configuration file.

To manually run MuMuDVB with your config type :

```shell
mumudvb -vvv -d -c /etc/mumudvb/card1.conf
```

**Comment by Infobarra** [comment] 2017-03-20 14:22
ok

thats how i was using it before..

the problem is i have 2 DVB cards , one with 4 tunners and 1 with 2 tunners, is it possible to add on script to launch all at the same time?

i am using embedded OEIPTV GUI interface also to monitor channels etc..

but i wanted to start all same time is it possible to start all card tunners, with different config.conf files for each one?

**Comment by kslimani** [comment] 2017-03-20 19:12
@Infobarra if i am not wrong, this is what the init script is intended for.

**EDIT: read my next comment**

~~If you have two adapters, the value of `ADAPTERS` in `/etc/default/mumudvb` should be something like :~~

```
ADAPTERS="0 1"
```

~~The first adapter is 0 and the second is 1.  To identify which card is 0 and 1 you can use the `lsdvb` command line. (`apt-get install dvb-apps` to install on Debian or Ubuntu)~~

~~And for examples add the two following lines also in `/etc/default/mumudvb` :~~

```
MUMUDVB_CONF_0="/etc/mumudvb/adapter_0.conf"
MUMUDVB_CONF_1="/etc/mumudvb/adapter_1.conf"
```

~~Basically, the init script just do a loop with ADAPTERS values and run one instance of mumudvb per adapter.~~

**Comment by kslimani** [comment] 2017-03-20 19:22
In fact, could you please copy paste the output of lsdvb command here please ?
Because if you have 4 tuners (_4 adapters_) on first card (_device 0_) and 2 tuners (_2 adapters_) on second card (_adapter 1_) then you may beed to configure like this (_sometimes it depend on drivers this is why i need your lsdvb output to confirm_) :

```
ADAPTERS="0 1 2 3 4 5"
```

```
# Device 0 (first card)
MUMUDVB_CONF_0="/etc/mumudvb/adapter_0.conf"
MUMUDVB_CONF_1="/etc/mumudvb/adapter_1.conf"
MUMUDVB_CONF_2="/etc/mumudvb/adapter_2.conf"
MUMUDVB_CONF_3="/etc/mumudvb/adapter_3.conf"

# Device 1 (second card)
MUMUDVB_CONF_4="/etc/mumudvb/adapter_4.conf"
MUMUDVB_CONF_5="/etc/mumudvb/adapter_5.conf"
```

**Comment by Infobarra** [comment] 2017-03-20 19:30
Ok this is an output example of my  cards detected.

total 6 tunners

/home/mumudvb# ls -l /dev/dvb/adapter*/
/dev/dvb/adapter0/:
total 0
crw-rw---- 1 root video 212, 0 Mar 16 13:15 demux0
crw-rw---- 1 root video 212, 1 Mar 16 13:15 dvr0
crw-rw---- 1 root video 212, 3 Mar 16 13:15 frontend0
crw-rw---- 1 root video 212, 2 Mar 16 13:15 net0

/dev/dvb/adapter1/:
total 0
crw-rw---- 1 root video 212, 4 Mar 16 13:15 demux0
crw-rw---- 1 root video 212, 5 Mar 16 13:15 dvr0
crw-rw---- 1 root video 212, 7 Mar 16 13:15 frontend0
crw-rw---- 1 root video 212, 6 Mar 16 13:15 net0

/dev/dvb/adapter2/:
total 0
crw-rw---- 1 root video 212,  8 Mar 16 13:15 demux0
crw-rw---- 1 root video 212,  9 Mar 16 13:15 dvr0
crw-rw---- 1 root video 212, 11 Mar 16 13:15 frontend0
crw-rw---- 1 root video 212, 10 Mar 16 13:15 net0

/dev/dvb/adapter3/:
total 0
crw-rw---- 1 root video 212, 12 Mar 16 13:15 demux0
crw-rw---- 1 root video 212, 13 Mar 16 13:15 dvr0
crw-rw---- 1 root video 212, 15 Mar 16 13:15 frontend0
crw-rw---- 1 root video 212, 14 Mar 16 13:15 net0

/dev/dvb/adapter4/:
total 0
crw-rw---- 1 root video 212, 17 Mar 16 13:15 demux0
crw-rw---- 1 root video 212, 18 Mar 16 13:15 dvr0
crw-rw---- 1 root video 212, 16 Mar 16 13:15 frontend0
crw-rw---- 1 root video 212, 19 Mar 16 13:15 net0

/dev/dvb/adapter5/:
total 0
crw-rw---- 1 root video 212, 21 Mar 16 13:15 demux0
crw-rw---- 1 root video 212, 22 Mar 16 13:15 dvr0
crw-rw---- 1 root video 212, 20 Mar 16 13:15 frontend0
crw-rw---- 1 root video 212, 23 Mar 16 13:15 net0






so card1.conf i left it only for mumudvb_conf_0= CARD1.CONF

AND 

card2.conf i left it only for mumudvb_conf_1= card2.conf



now how can i start mumudvb and get mumu to execture card1.conf and card2.conf scan at the same time? but ofcourse creating 2 separate streams?


i was using this cmd before  sudo mumudvb -vvv -d -c /etc/default/mumudvb  
but aparently this is wrong so i am lost on how to do it?

**Comment by kslimani** [comment] 2017-03-20 19:50
@Infobarra you have 6 adapters, so you need 6 configuration files, check my previous comment (_if you use the 6 tuners to tune on 6 frenquencies that is_)

Can you run `mumudvb -l` and copy paste output please. (_it is like lsdvb command, it list your adapters_)

When you have created the configuration files for all tunes, you can run all with single command `service start mumudvb`

**Comment by Infobarra** [comment] 2017-03-20 19:51
hi kslimani

please find attached the information requested

lsdvb

                lsdvb: Simple utility to list PCI/PCIe DVB devices
                Version: 0.0.4
                Copyright (C) Manu Abraham

cx23885 (14:8852 6981:8888) on PCI Domain:0 Bus:9 Device:0 Function:0
        DEVICE:0 ADAPTER:4 FRONTEND:0 (TurboSight TBS 6981 DVBS/S2 frontend)
                 FE_QPSK Fmin=950MHz Fmax=2150MHz
        DEVICE:0 ADAPTER:0 FRONTEND:0 (TurboSight TBS 6904 DVBS/S2 frontend)
                 FE_QPSK Fmin=950MHz Fmax=2150MHz
        DEVICE:0 ADAPTER:3 FRONTEND:0 (TurboSight TBS 6904 DVBS/S2 frontend)
                 FE_QPSK Fmin=950MHz Fmax=2150MHz
        DEVICE:0 ADAPTER:2 FRONTEND:0 (TurboSight TBS 6904 DVBS/S2 frontend)
                 FE_QPSK Fmin=950MHz Fmax=2150MHz
        DEVICE:0 ADAPTER:5 FRONTEND:0 (TurboSight TBS 6981 DVBS/S2 frontend)
                 FE_QPSK Fmin=950MHz Fmax=2150MHz
        DEVICE:0 ADAPTER:1 FRONTEND:0 (TurboSight TBS 6904 DVBS/S2 frontend)
                 FE_QPSK Fmin=950MHz Fmax=2150MHz

**Comment by m0yellow** [comment] 2017-03-20 20:02
mumudvb -c <exact-one-config-file>

**Comment by kslimani** [comment] 2017-03-20 20:02
OK, this output confirm that adapters 0, 1, 2 and 3 are TBS 6904 card and adapters 4 and 5 are TBS 6981  card.

For example, let's say you want to use **only 2 tuners** : the adapter 1 on TBS 6904 (second F connector input) and the 4 on TBS6981 (first F connector input). (i choosed non-following inputs on purpose so you understand the mechanics of init script)

Then edit  `/etc/default/mumudvb` file :

```
ADAPTERS="1 4"
```

```
# TBS 6904 (adapter 1)
MUMUDVB_CONF_1="/etc/mumudvb/adapter_1.conf"

# TBS 6981 (adapter 4)
MUMUDVB_CONF_4="/etc/mumudvb/adapter_4.conf"
```

Create the `adapter_1.conf` and `adapter_4.conf` files with proper configuration in `/etc/mumudvb/`.

Finally, start mumudvb instances by running init script :

```
/etc/init.d/mumudvb start
```

Or using service command (_which is basically the same_) :

```
service mumudvb start
```

**Comment by Infobarra** [comment] 2017-03-20 20:16
yup thats exactly how i have it now running.

Now i have another question does anyone here have OEIPTV running as GUI? i managed to get it running and made some changes on the code Mysql to store autoconfiguration data etc..

but now i have a issue on setting up the  multicast_ip on autoconf_ip4=239.101.%card.%number

i am using a varchar 100 in mysql to store the data but when i export to the card1.conf file it comes out like this


autoconf_ip4=239.106.˲d.%number 


this is my mysql data
UPDATE  `oeiptv`.`config` SET  `value` =  '239.106.%card.%number' WHERE  `config`.`id` =10;

this way it auto selects the card number and channel id number to generate the multicast ip4

**Closed as completed** 2019-09-18 22:05 UTC
